### PR TITLE
compiler warnings about Deprecated annotation

### PR DESCRIPTION
**Pull request by pjfanning**
see #554

### CODE REVIEW

**Comment by He-Pin** [comment]
Not sure Idea will support this, I think it was there for Java user？

**Comment by He-Pin** [comment]
Lgtm，We can starting remove them.after.1.1.x

**Review by He-Pin — APPROVED** [review]

**Comment by laglangyue** [comment]
lgtm,but ci failed

**Review by He-Pin — APPROVED** [review]

**Review by raboof — COMMENTED** [review]
These are Java DSLs. I think they were originally there to make sure any Java tooling would also see the Deprecated state of these methods.

I seem to remember perhaps newer Scala compiler versions will automatically emit a Java `@Deprecated` annotation when you use the Scala `@deprecated` annotation. Have we checked that this is the case of all Scala compiler versions that we build with?

**Comment by He-Pin** [comment]
The question is ,Will scala generate the `@Deprecated` annotation in classfile too ,and since Java 9, the java one can have a `since` filed too.

**Pull request closed without merging**
