### PR TITLE
protobuf-java upgrade

### PR DESCRIPTION
**Pull request by jbaranski**
Address the following known issues with protobuf-java:
https://security.snyk.io/vuln/SNYK-JAVA-COMGOOGLEPROTOBUF-3167772
https://security.snyk.io/vuln/SNYK-JAVA-COMGOOGLEPROTOBUF-3167774

Before/after the fix, run:
```
sbt dependencyTree > output.log && grep -A1 -B1 "protobuf-java" output.log
```

*Output before*
```
...
[info]               +-com.google.protobuf:protobuf-java:3.19.6
...
```

*Output after*
```
...
[info]   |           +-com.google.protobuf:protobuf-java:3.19.6 (evicted by: 3.21.12)
[info]   |           +-com.google.protobuf:protobuf-java:3.21.12
...
```

### CODE REVIEW

**Comment by jbaranski** [comment]
@pjfanning Hi, can you please take a look? 

Also what is the best way to contact you why I made this PR (users-help@pekko.apache.org <users-help@pekko.apache.org>)? I'd like to just tell you why I did this before putting it on the PR or public mailing list.

**Comment by laglangyue** [comment]
You should not directly contact PMC to explain why. You should clearly describe the reason for the change in ISSUE or PR.

**Comment by jbaranski** [comment]
> You should not directly contact PMC to explain why. You should clearly describe the reason for the change in ISSUE or PR.

Thanks, done.

**Comment by pjfanning** [comment]
https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java - v3.19.6 has no CVEs. The issues that you highlight appear to be fixed in v3.19.6.

**Comment by jbaranski** [comment]
> https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java - v3.19.6 has no CVEs. The issues that you highlight appear to be fixed in v3.19.6.

Yes, I glossed over this... apologies for the noise.

**Comment by pjfanning** [comment]
I don't think this is needed so -1 from me.

protobuf-java is just a transitive dependency of org.apache.pekko:pekko-http-scalafix-rules and not pekko-http generally 

via
```
[info]       +-org.scalameta:parsers_2.13:4.9.1 [S]
[info]         +-org.scalameta:trees_2.13:4.9.1 [S]
[info]           +-org.scalameta:common_2.13:4.9.1 [S]
[info]             +-com.lihaoyi:sourcecode_2.13:0.3.1 [S]
[info]             +-com.thesamet.scalapb:scalapb-runtime_2.13:0.11.15 [S]
[info]               +-com.google.protobuf:protobuf-java:3.19.6
```

**Pull request closed without merging**
